# Required 
ScreenType: 'enrichment' 
LibFilename: 'GeCKOv21_Human.tsv' 

# Library Parameters 
LibFilename: 'GeCKOv21_Human.tsv'       
seq_5_end: 'TCTTGTGGAAAGGACGAAACACCN'  
NonTargetPrefix: 'NonTargeting'        
NumGuidesPerGene: 6                       
                                       

# Alignment 
sgRNALength: 20 
CutErrorTol: 0.1 
AS_min: 40 
Theta: 2 
L_bw: 11 
N_bw: 1 
i_bw: 'S,1,0.75' 
AlnOutput: 'Delete' 
keepCutReads: False 
delta: 1 
R_min: 20 

# Read Counting 
Normalization: 'cpm' 
Cutoff: 0 
RoundCount: False 

# Gene Ranking 
GeneMetric: 'aRRA' 
Np: 1000 
P_0: 0.00005 
thr_STARS: 10 

# Statistical Significance 
alpha_s: 0.001 
alpha_g: 0.01 
padj: 'fdr_bh' 

# Sample Clustering 
ClusterBy: 'variance' 
TopN: 25 

# Visualization 
dotsize: 10 
TransparencyLevel: 0.1 
scatter_annotate: False 
ShowNonTargets: False 
logbase: 10 
width_p: 800 
height_p: 800 
fontsize_p: 14 
marginsize: 10 
max_q: 95 
svg: True 
dpi: 300 
HitListFormat: 'tsv' 

WorkingDir: '/workingdir/'
DataDir: '/workingdir/Data/'
TempDataDir: '/workingdir/TempData/'
LibDir: '/workingdir/Library/'
IndexDir: '/workingdir/Library/Bowtie2_Index/'
ScriptsDir: '/opt/PinAPL-Py/Scripts/'
AlignDir: '/workingdir/Alignments/'
AnalysisDir: '/workingdir/Analysis/'
TrimLogDir: '/workingdir/Analysis/Read_Trimming'
HitDir: '/workingdir/Analysis/sgRNA_Rankings'
GeneDir: '/workingdir/Analysis/Gene_Rankings'
ControlDir: '/workingdir/Analysis/Control/'
HeatDir: '/workingdir/Analysis/Heatmap/'
AlnQCDir: '/workingdir/Analysis/Alignment_Statistics/'
CountQCDir: '/workingdir/Analysis/ReadCount_Statistics/'
ScatterDir: '/workingdir/Analysis/ReadCount_Scatterplots/'
HiLiteDir: '/workingdir/Analysis/ReadCount_Scatterplots/Highlighted_Genes/'
CorrelDir: '/workingdir/Analysis/Replicate_Correlation/'
HiLiteDir2: '/workingdir/Analysis/Replicate_Correlation/Highlighted_Genes'
EffDir: '/workingdir/Analysis/sgRNA_Efficacy/'
DepthDir: '/workingdir/Analysis/Read_Depth/'
SeqQCDir: '/workingdir/Analysis/Sequence_Quality/'
pvalDir: '/workingdir/Analysis/p-values/' 
LogFileDir: '/workingdir/Analysis/Log_File/'
bw2Dir: '/usr/bin/'
CutAdaptDir: '/root/.local/bin/'   
STARSDir: '/opt/PinAPL-Py/Scripts/STARS_mod/'

SanityScript: 'CheckCharacters'
IndexScript: 'BuildLibraryIndex'
LoaderScript: 'LoadDataSheet'
ReadDepthScript: 'PlotNumReads'
SeqQCScript: 'CheckSequenceQuality'
TrimScript: 'TrimReads'
AlignScript: 'AlignReads'
NormalizeScript: 'NormalizeReadCounts'
StatsScript: 'AnalyzeReadCounts'
ControlScript: 'AnalyzeControl'
sgRNARankScript: 'FindHits'
GeneRankScript: 'RankGenes'
ScatterScript: 'PlotCounts'
ReplicateScript: 'PlotReplicates'
ClusterScript: 'PlotHeatmap'
