# Required 
ScreenType: 'enrichment' 
LibFilename: 'GeCKOv2_Human.tsv' 

# Library Parameters 

LibFilename: 'GeCKOv2_Human.tsv'            # filename of library spreadsheet  
seq_5_end: 'TCTTGTGGAAAGGACGAAACACCN'       # sequence 5' of sgRNA in read       # sequence 3' of sgRNA in read
NonTargetPrefix: 'NonTargeting'        # prefix for non-targeting sgRNAs in library (keep at default if none present)
NumGuidesPerGene: 6                       # number of sgRNAs targeting each gene (excluding non-targeting controls and miRNAs). 
                                       #    ONLY IMPORTANT IF 'ES' is chosen for gene ranking method !

# Read Counting 
Normalization: 'cpm' 
Cutoff: 0 
RoundCount: False 

# Heatmap 
ClusterBy: 'variance' 
TopN: 25 

# Gene Ranking 
GeneMetric: 'aRRA' 
P_0: 0.005 
Np: 1000 
thr_STARS: 10 

# Statistical Significance 
alpha: 0.1 
padj: 'fdr_bh' 

# Adapter Trimming 
R_min: 10 
CutErrorTol: 0.25 

# Alignment 
AlnOutput: 'Delete' 
keepCutReads: False 
Theta: 2 
L_bw: 11 
N_bw: 1 
i_bw: 'S,1,0.75' 
delta: 1 
AS_min: 40 

# Output Formatting 
dpi: 300 
dotsize: 10 
logbase: 10 
width_p: 800 
height_p: 800 
fontsize_p: 14 
marginsize: 10 
scatter_annotate: False 
max_q: 95 
svg: True 
HitListFormat: 'tsv' 
TransparencyLevel: 0.1 
ShowNonTargets: False 

WorkingDir: '/workingdir/'
DataDir: '/workingdir/Data/'
LibDir: '/workingdir/Library/'
IndexDir: '/workingdir/Library/Bowtie2_Index/'
ScriptsDir: '/opt/PinAPL-Py/Scripts/'
AlignDir: '/workingdir/Alignments/'
AnalysisDir: '/workingdir/Analysis/'
HitDir: '/workingdir/Analysis/sgRNA_Rankings'
GeneDir: '/workingdir/Analysis/Gene_Rankings'
ControlDir: '/workingdir/Analysis/Control/'
HeatDir: '/workingdir/Analysis/Heatmap/'
AlnQCDir: '/workingdir/Analysis/Alignment_Statistics/'
CountQCDir: '/workingdir/Analysis/ReadCount_Statistics/'
ScatterDir: '/workingdir/Analysis/ReadCount_Scatterplots/'
HiLiteDir: '/workingdir/Analysis/ReadCount_Scatterplots/Highlighted_Genes/'
CorrelDir: '/workingdir/Analysis/Replicate_Correlation/'
EffDir: '/workingdir/Analysis/sgRNA_Efficacy/'
DepthDir: '/workingdir/Analysis/Read_Depth/'
SeqQCDir: '/workingdir/Analysis/Sequence_Quality/'
pvalDir: '/workingdir/Analysis/p-values/' 
LogFileDir: '/workingdir/Analysis/Log_File/'
bw2Dir: '/usr/bin/'
CutAdaptDir: '/root/.local/bin/'   
STARSDir: '/opt/PinAPL-Py/Scripts/STARS_mod/'

IndexScript: 'BuildLibraryIndex'
LoaderScript: 'LoadDataSheet'
ReadDepthScript: 'PlotNumReads'
SeqQCScript: 'CheckSequenceQuality'
AlignScript: 'AlignReads'
NormalizeScript: 'NormalizeReadCounts'
StatsScript: 'AnalyzeReadCounts'
ControlScript: 'AnalyzeControl'
sgRNARankScript: 'FindHits'
GeneRankScript: 'RankGenes'
ScatterScript: 'PlotCounts'
ReplicateScript: 'PlotReplicates'
ClusterScript: 'PlotHeatmap'
